---
- name: R1 ACL
  hosts: R1
  gather_facts: false
  connection: local

  tasks:
    - name: R1 ACL Set
      ios_command:
        commands:
          - config terminal
          - access-list 179 permit tcp 192.168.44.0 0.0.0.255 192.168.44.3 0.0.0.0
          - access-list 179 permit udp 192.168.44.0 0.0.0.255 192.168.44.3 0.0.0.255
      register: acl

    
- name: R2 ACL
  hosts: R2
  gather_facts: false
  connection: local

  tasks:
    - name: R1 ACL Set
      ios_command:
        commands:
          - config terminal
          - access-list 186 permit tcp 192.168.2.0 0.0.0.255 192.168.2.3 0.0.0.0
          - access-list 186 permit udp 192.168.2.0 0.0.0.255 192.168.2.3 0.0.0.255
      register: acl